# Generated by Django 6.0.2 on 2026-03-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_toolresultlink_tool_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentlink',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='agentlink',
            name='is_background',
        ),
        migrations.RemoveField(
            model_name='agentlink',
            name='result_count',
        ),
        migrations.RemoveField(
            model_name='agentlink',
            name='started_at',
        ),
    ]
