# Generated by Django 6.0.2 on 2026-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_simplify_agent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlink',
            name='is_background',
            field=models.BooleanField(default=False),
        ),
    ]
