# Generated by Django 6.0.2 on 2026-03-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_is_background_to_agent_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlink',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
