# Generated by Django 6.0.2 on 2026-03-09 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_session_effort_thinking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlashCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('commands_dir', 'Commands directory'), ('skills_dir', 'Skills directory'), ('plugin', 'Plugin')], max_length=20)),
                ('plugin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('argument_hint', models.CharField(blank=True, max_length=200, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slash_commands', to='core.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='unique_slash_command_per_project', nulls_distinct=False)],
            },
        ),
    ]
