# Generated by Django 6.0.2 on 2026-03-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_slash_command'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slashcommand',
            name='unique_slash_command_per_project',
        ),
        migrations.AddIndex(
            model_name='slashcommand',
            index=models.Index(fields=['project', 'name'], name='idx_slash_command_project_name'),
        ),
    ]
