# Generated by Django 6.0.4 on 2026-04-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_session_provider_not_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usagesnapshot',
            name='seven_day_cowork_resets_at',
        ),
        migrations.RemoveField(
            model_name='usagesnapshot',
            name='seven_day_cowork_utilization',
        ),
        migrations.RemoveField(
            model_name='usagesnapshot',
            name='seven_day_oauth_apps_resets_at',
        ),
        migrations.RemoveField(
            model_name='usagesnapshot',
            name='seven_day_oauth_apps_utilization',
        ),
        migrations.RemoveField(
            model_name='usagesnapshot',
            name='seven_day_opus_resets_at',
        ),
        migrations.RemoveField(
            model_name='usagesnapshot',
            name='seven_day_opus_utilization',
        ),
        migrations.RemoveField(
            model_name='usagesnapshot',
            name='seven_day_sonnet_resets_at',
        ),
        migrations.RemoveField(
            model_name='usagesnapshot',
            name='seven_day_sonnet_utilization',
        ),
    ]
