# Generated by Django 6.0.4 on 2026-05-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_session_file_path_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='provider',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
