# Generated by Django 6.0.4 on 2026-05-13 22:54
"""Squash of migrations 0089 → 0092 — every step that followed the
``Command`` model creation in 0088:

- 0089: drop the legacy ``SlashCommand`` model
- 0090: swap the lookup index from ``(provider, project, name)`` to
  ``(provider, activation_char, project)``
- 0091: drop the unused ``source`` column
- 0092: add the ``is_builtin`` flag

The original four migrations stay on disk for now (the standard Django
flow): instances that already applied them get the squashed marked as
applied via ``replaces``. Once every environment has caught up, the
four originals plus this file's ``replaces`` can be removed in a
follow-up commit.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0089_delete_slashcommand'), ('core', '0090_command_index_swap_name_for_activation_char'), ('core', '0091_drop_command_source'), ('core', '0092_command_is_builtin')]

    dependencies = [
        ('core', '0088_add_command'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlashCommand',
        ),
        migrations.RemoveIndex(
            model_name='command',
            name='idx_command_prov_proj_name',
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['provider', 'activation_char', 'project'], name='idx_command_prov_act_proj'),
        ),
        migrations.RemoveField(
            model_name='command',
            name='source',
        ),
        migrations.AddField(
            model_name='command',
            name='is_builtin',
            field=models.BooleanField(default=False),
        ),
    ]
