# Generated by Django 6.0.4 on 2026-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_delete_slashcommand_squashed_0092_command_is_builtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fast_mode',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
