# Generated by Django 6.0.4 on 2026-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_session_fast_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagesnapshot',
            name='extra_usage_remaining_credits',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
