# Generated by Django 6.0.4 on 2026-05-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_processrun_awaiting_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='question_widget',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
