# Generated by Django 6.0.4 on 2026-05-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_session_question_widget'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='idx_session_visible',
        ),
        migrations.AddField(
            model_name='session',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='spawned_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_sessions', to='core.session'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(condition=models.Q(('created_at__isnull', False), ('hidden', False), ('type', 'session'), ('user_message_count__gt', 0)), fields=['project', '-mtime'], name='idx_session_visible'),
        ),
    ]
