# Generated by Codex on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_session_hidden_and_spawned_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="spawn_root",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spawn_tree_sessions",
                to="core.session",
            ),
        ),
    ]
