# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_session_spawn_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="annotations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
