# Generated by Claude on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_session_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="system_prompt_addendum",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
