# Generated by Django 6.0.4 on 2026-06-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_session_system_prompt_addendum'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='worktree_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worktrees', to='core.project'),
        ),
    ]
