# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_project_worktree_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='trust',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='trust_propagation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='trust_imported',
            field=models.BooleanField(default=False),
        ),
    ]
