# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_project_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='default_agent_settings',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
