# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_project_agent_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='worktree_directory',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
