# Generated by Django 6.0.4 on 2026-06-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_project_worktree_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hybrid',
            field=models.BooleanField(default=False),
        ),
    ]
