# Generated by Django 6.0.4 on 2026-06-16 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_session_hybrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('workspace', 'Workspace'), ('all', 'All projects')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_bookmarks', to='core.project')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_bookmarks', to='core.session')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['project'], name='idx_artifactbookmark_project')],
                'constraints': [models.UniqueConstraint(fields=('session', 'relative_path'), name='uniq_artifact_bookmark_session_path')],
            },
        ),
    ]
