# Generated by Django 6.0.4 on 2026-06-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_artifact_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactbookmark',
            name='allowed_hosts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
