# Generated by Django 6.0.4 on 2026-06-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_artifactbookmark_allowed_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
