# Generated by Django 6.0.4 on 2026-06-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_session_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_layout_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
