# Generated by Django 6.0.4 on 2026-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_project_default_layout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='tasks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
