# Generated by Django 6.0.4 on 2026-06-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_session_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='has_workflows',
            field=models.BooleanField(default=False),
        ),
    ]
