# Generated by Django 6.0.4 on 2026-06-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_session_has_workflows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='agent_id',
        ),
    ]
