# Generated by Django 6.0.4 on 2026-06-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='script_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workflow',
            name='synthesis',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
