# Generated by Django 6.0.4 on 2026-06-28 07:10

from decimal import Decimal

from django.db import migrations, models


def _backfill_cost(apps, schema_editor):
    """Set each existing Workflow's cost = sum of its agent sessions' total_cost.

    Workflow agents are Sessions keyed ``<run_id>:<agent_id>``; their total_cost
    already rolls up nested subagents. New rows compute this at write time; this
    one-shot backfill brings rows that were ingested before the column existed.
    """
    Workflow = apps.get_model("core", "Workflow")
    Session = apps.get_model("core", "Session")
    for wf in Workflow.objects.all():
        costs = Session.objects.filter(id__startswith=f"{wf.run_id}:").values_list("total_cost", flat=True)
        wf.cost = sum((c for c in costs if c is not None), Decimal("0"))
        wf.save(update_fields=["cost"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_workflow_synthesis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.RunPython(_backfill_cost, migrations.RunPython.noop),
    ]
