# Generated by Django 6.0.4 on 2026-06-28 07:27

import json
from decimal import Decimal

from django.db import migrations, models


def _backfill_phases_cost(apps, schema_editor):
    """Set each existing Workflow's phases_cost = per-phase agent cost breakdown.

    Mirrors ``Workflow.compute_costs``: parse the stored envelope, group each
    agent's session total_cost by the 1-based phaseIndex it was stamped with.
    New rows compute this at write time; this backfills rows ingested before the
    column existed.
    """
    Workflow = apps.get_model("core", "Workflow")
    Session = apps.get_model("core", "Session")
    for wf in Workflow.objects.all():
        try:
            envelope = json.loads(wf.raw_json)
        except (ValueError, TypeError):
            envelope = {}
        prefix = f"{wf.run_id}:"
        by_agent = {
            sid[len(prefix):]: cost
            for sid, cost in Session.objects.filter(id__startswith=prefix).values_list("id", "total_cost")
        }
        phases: dict[str, Decimal] = {}
        for entry in (envelope or {}).get("workflowProgress", []):
            if entry.get("type") != "workflow_agent":
                continue
            idx = entry.get("phaseIndex")
            cost = by_agent.get(entry.get("agentId"))
            if idx is None or cost is None:
                continue
            key = str(idx)
            phases[key] = phases.get(key, Decimal("0")) + cost
        wf.phases_cost = {k: float(v) for k, v in phases.items()}
        wf.save(update_fields=["phases_cost"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_workflow_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='phases_cost',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(_backfill_phases_cost, migrations.RunPython.noop),
    ]
