# Generated by Django 6.0.4 on 2026-07-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_command_is_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
