# Generated by Django 6.0.4 on 2026-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_session_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='plan_paths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
