# Generated by Django 6.0.4 on 2026-07-08 07:42

import django.db.models.deletion
import twicc.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_session_browser_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.CharField(default=twicc.core.models.generate_share_id, max_length=16, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('session', 'session'), ('artifact', 'artifact')], max_length=16)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('notify_on_view', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_bookmark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.artifactbookmark')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='core.share')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['kind'], name='idx_share_kind'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artifact_bookmark__isnull', True), ('kind', 'session'), ('session__isnull', False)), models.Q(('artifact_bookmark__isnull', False), ('kind', 'artifact'), ('session__isnull', True)), _connector='OR'), name='share_target_matches_kind'),
        ),
        migrations.AddIndex(
            model_name='shareaccess',
            index=models.Index(fields=['share', '-at'], name='idx_shareaccess_share_at'),
        ),
    ]
