# Generated by Django 6.0.4 on 2026-07-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactbookmark',
            name='denied_hosts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ArtifactNetworkDenial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_key', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=16)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_at', models.DateTimeField(auto_now_add=True)),
                ('last_at', models.DateTimeField(auto_now=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_denials', to='core.artifactbookmark')),
                ('share', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_denials', to='core.share')),
            ],
            options={
                'ordering': ['-last_at'],
                'indexes': [models.Index(fields=['bookmark', '-last_at'], name='idx_netdenial_bookmark_at')],
            },
        ),
    ]
