# Generated by Django 6.0.4 on 2026-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_artifact_network_denial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('reasoning_effort', models.CharField(max_length=10)),
                ('pass_at_1', models.FloatField(blank=True, null=True)),
                ('pass_at_4', models.FloatField(blank=True, null=True)),
                ('mean_cost_usd', models.FloatField(blank=True, null=True)),
                ('median_duration_seconds', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'model', 'reasoning_effort'), name='uniq_mb_prov_model_effort')],
            },
        ),
    ]
