# Generated by Django 6.0.4 on 2026-07-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_project_browser_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagesnapshot',
            name='extra_usage_currency',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='usagesnapshot',
            name='extra_usage_decimal_places',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
