# Generated by Django 6.0.4 on 2026-07-24 20:44

import django.db.models.deletion
import twicc.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_project_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.CharField(default=twicc.core.models.generate_peer_id, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('remote_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('base_url', models.URLField(max_length=500)),
                ('state', models.CharField(choices=[('pending_sent', 'Pending (sent)'), ('pending_received', 'Pending (received)'), ('active', 'Active'), ('broken', 'Broken')], max_length=20)),
                ('token_ours', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('token_theirs', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('verification_code', models.CharField(blank=True, default='', max_length=6)),
                ('verification_attempts', models.PositiveSmallIntegerField(default=0)),
                ('verification_regens', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('code_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('remote_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=3)),
                ('message_id', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('attachments_meta', models.JSONField(default=list)),
                ('origin', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('refused', 'Refused'), ('failed', 'Failed')], max_length=12)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_to_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_messages_received', to='core.session')),
                ('origin_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_messages_sent', to='core.session')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.peer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'direction'], name='idx_peermessage_status')],
                'constraints': [models.UniqueConstraint(fields=('peer', 'direction', 'message_id'), name='uniq_peermessage_peer_direction_msgid')],
            },
        ),
    ]
