# Generated by Django 6.0.4 on 2026-08-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_peermessage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='created_by_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shares', to='core.session'),
        ),
    ]
